### ISSUE TITLE
After creating a new game, GUI sends Moves to all previous games (?)

### ISSUE THREAD

**Issue by anarchuser** [CAU-Kiel-Tech-Inf/gui#56] opened 2020-11-09 11:37 UTC
I created a few new Games (using the Ctrl+N shortcut), Human-Human.
Then I wanted to place a piece.
The corresponding SetMove was sent out several times to different room IDs in quick succession:
```
12:27:36 DEBUG sc.networking.clients.XStreamClient - Client sc.networking.clients.LobbyClient@3461614e: Sending RoomPacket(roomId=2ae8094b-8169-4e5e-94f2-4f65b532cd97, data=BLUE Piece PENTO_T:2 [0,17]) via TcpNetwork{socket=Socket[addr=localhost/127.0.0.1,port=13050,localport=45898]}
12:27:36 DEBUG sc.networking.clients.XStreamClient - Client sc.server.network.Client@113c51fe: Received RoomPacket(roomId=2ae8094b-8169-4e5e-94f2-4f65b532cd97, data=BLUE Piece PENTO_T:2 [0,17]) via TcpNetwork{socket=Socket[addr=/127.0.0.1,port=45898,localport=13050]}
12:27:36 DEBUG sc.networking.clients.XStreamClient - Client sc.networking.clients.LobbyClient@5ff30637: Sending RoomPacket(roomId=4efc7500-a8d5-4ca9-bd71-3007cba048a3, data=BLUE Piece PENTO_T:2 [0,17]) via TcpNetwork{socket=Socket[addr=localhost/127.0.0.1,port=13050,localport=45910]}
12:27:36 DEBUG sc.networking.clients.XStreamClient - Client sc.networking.clients.LobbyClient@65835484: Sending RoomPacket(roomId=c1c2b02d-6214-4fa3-9f3d-b10168242ff4, data=BLUE Piece PENTO_T:2 [0,17]) via TcpNetwork{socket=Socket[addr=localhost/127.0.0.1,port=13050,localport=45924]}
12:27:36 DEBUG sc.networking.clients.XStreamClient - Client sc.server.network.Client@404a77c: Received RoomPacket(roomId=4efc7500-a8d5-4ca9-bd71-3007cba048a3, data=BLUE Piece PENTO_T:2 [0,17]) via TcpNetwork{socket=Socket[addr=/127.0.0.1,port=45910,localport=13050]}
12:27:36 DEBUG sc.networking.clients.XStreamClient - Client sc.networking.clients.LobbyClient@47d2099a: Sending RoomPacket(roomId=b8f31ee6-dc8a-4f4a-8c2e-89e23a875c07, data=BLUE Piece PENTO_T:2 [0,17]) via TcpNetwork{socket=Socket[addr=localhost/127.0.0.1,port=13050,localport=45904]}
```
As response I've got a rule violation error back for every move sent except the last (which was actually valid).
They GUI received these errors and stopped the Game:
![image](https://user-images.githubusercontent.com/5949896/98536553-48f75f00-2288-11eb-8ce8-e4b5d848fd13.png)

**Comment by SKoschnicke** [comment] 2020-11-19 08:02
Duplicate of #57

**Closed by SKoschnicke** 2020-11-19 08:02 UTC
